name: proot_many_archs_static
on:
  schedule:
    - cron: "0 6 * * 0"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      
    - name: Install talloc
      run: |
        wget -c "https://www.samba.org/ftp/talloc/talloc-2.4.2.tar.gz"
        tar xvf talloc-2.4.2.tar.gz
        cd talloc-2.4.2/
        ./configure waf configure
        make
        sudo make install
        cd ..

    - name: Compile and extract artifacts from docker container
      run: |
        mkdir -p dist

        for arch in x86_64 aarch64 armhf i386; do
          docker build --platform "${arch}" -t alpine:proot .
          docker run --rm --platform "${arch}" -v $(pwd):/workdir alpine:proot cp /proot/build/proot "/workdir/dist/proot-${arch}"
        done

    - name: Set permissions for dist directory
      run: |
        sudo chown -R "$(id -u)":"$(id -g)" dist/
        sudo chmod -R 766 dist/

    - name: Upload artifacts to release
      uses: actions/upload-artifact@v4
      with:
        name: proot
        path: 'dist'

    - name: Compute Short SHA
      id: ssha
      run: |
        echo "ssha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    outputs:
      ssha: ${{ steps.ssha.outputs.ssha }}


  release:
      permissions: write-all
      needs: [build]
      runs-on: ubuntu-latest

      steps:
        - uses: actions/download-artifact@v4
          with:
            name: proot

        - name: release
          uses: marvinpinto/action-automatic-releases@latest
          with:
            title: Continuous ${{ needs.build.outputs.ssha }}
            automatic_release_tag: ${{ needs.build.outputs.ssha }}
            prerelease: false
            draft: false
            files: |
              *proot*
            repo_token: ${{ secrets.GITHUB_TOKEN }}
